### ISSUE TITLE
Doesn't appear to work with numpy 1.7.0

### ISSUE THREAD

**Issue by orangeduck** [martinling/numpy_quaternion#6] opened 2013-02-23 12:06 UTC
When attempting to use with numpy 1.7.0 I get the following:

```
Python 2.6.6 (r266:84297, Aug 24 2010, 18:13:38) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> print np.__version__
1.7.0
>>> import quaternion
>>> print np.quaternion
<type 'quaternion.quaternion'>
>>> np.quaternion(1,2,3,4)
(1.0, 2.0, 3.0, 4.0)
>>> np.quaternion(1,2,3,4) * np.quaternion(1,2,3,4)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: can't multiply sequence by non-int of type 'tuple'
>>>
```

It appears that the np.quaternion is just returning a tuple of the arguments passed in. I think the API for numpy must have changed.

**Comment by nocnokneo** [comment] 2013-08-22 14:18
I'm experiencing the same issue using numpy 1.7.1. Are there updates on this issue? Maybe hints on how I could go about fixing it?

**Comment by thoppe** [comment] 2013-09-11 19:09
I've seen the same issue. The type returned by 

```
np.quaternion(1,2,3,4)
```

is a `tuple` which is the cause of the error. Not sure why this is the case.

**Comment by moble** [comment] 2016-08-27 13:24
This problem is fixed in a newer version of this package, found [here](https://github.com/moble/quaternion).

**Closed as completed** 2016-08-27 16:32 UTC
